# GitHub Actions
# https://help.github.com/en/articles/configuring-a-workflow
name: Cypress tests

on: [workflow_dispatch]

jobs:
  testerloop-chrome-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Package Registry
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: echo "//npm.pkg.github.com/:_authToken=${{secrets.NPM_TOKEN}}" >> ~/.npmrc
      - name: Download the build folders
        uses: actions/download-artifact@v3
      - name: install dependencies and verify Cypress
        run: |
          npm install 
          npx cypress verify

        # Starts local server, then runs Cypress tests
      - name: Cypress tests on single thread
        run: |
          npm run e2e
      - uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: cypress-poc/cypress/screenshots
      - uses: actions/upload-artifact@v3
        with:
          name: videos
          path: cypress-poc/cypress/videos
