name: Run Unit Tests

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  packages: read
  pull-requests: write

jobs:
  test:
    name: Run Jest tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Install npm dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:cov -- --coverageReporters json-summary
      
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
